name: PVPManager
main: net.saopj.pvpmanager.Main
version: 1.0.0
author: [ShallowAi, GlowingBedrock]
softdepend: [VexView]
commands:
  pvpmanger:
    description: "PVPManger命令"
    usage: /pvpmanger
    aliases: [pm,pvpm]
    permission: "pvpm.base"
    permission-message: "权限不足"